Document: simplesnap
Title: Debian simplesnap Manual
Author: <insert document author here>
Abstract: This manual describes what simplesnap is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/simplesnap/simplesnap.sgml.gz

Format: postscript
Files: /usr/share/doc/simplesnap/simplesnap.ps.gz

Format: text
Files: /usr/share/doc/simplesnap/simplesnap.text.gz

Format: HTML
Index: /usr/share/doc/simplesnap/html/index.html
Files: /usr/share/doc/simplesnap/html/*.html
